In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
df=pd.read_csv('bank-full.csv',sep=';')
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [4]:
df.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [5]:
df.shape

(45211, 17)

In [6]:
df= pd.get_dummies(df, columns=['job','marital','education','contact','month','poutcome', 'default', 'housing', 'loan','y'], drop_first=True)
df

age  balance  day  duration  campaign  pdays  previous  \
0       58     2143    5       261         1     -1         0   
1       44       29    5       151         1     -1         0   
2       33        2    5        76         1     -1         0   
3       47     1506    5        92         1     -1         0   
4       33        1    5       198         1     -1         0   
...    ...      ...  ...       ...       ...    ...       ...   
45206   51      825   17       977         3     -1         0   
45207   71     1729   17       456         2     -1         0   
45208   72     5715   17      1127         5    184         3   
45209   57      668   17       508         4     -1         0   
45210   37     2971   17       361         2    188        11   

       job_blue-collar  job_entrepreneur  job_housemaid  ...  month_nov  \
0                    0                 0              0  ...          0   
1                    0                 0              0  ...          0   
2                    0                 1              0  ...          0   
3                    1                 0              0  ...          0   
4                    0                 0              0  ...          0   
...                ...               ...            ...  ...        ...   
45206                0                 0              0  ...          1   
45207                0                 0              0  ...          1   
45208                0                 0              0  ...          1   
45209                1                 0              0  ...          1   
45210                0                 1              0  ...          1   

       month_oct  month_sep  poutcome_other  poutcome_success  \
0              0          0               0                 0   
1              0          0               0                 0   
2              0          0               0                 0   
3              0          0               0                 0   
4              0          0               0                 0   
...          ...        ...             ...               ...   
45206          0          0               0                 0   
45207          0          0               0                 0   
45208          0          0               0                 1   
45209          0          0               0                 0   
45210          0          0               1                 0   

       poutcome_unknown  default_yes  housing_yes  loan_yes  y_yes  
0                     1            0            1         0      0  
1                     1            0            1         0      0  
2                     1            0            1         1      0  
3                     1            0            1         0      0  
4                     1            0            0         0      0  
...                 ...          ...          ...       ...    ...  
45206                 1            0            0         0      1  
45207                 1            0            0         0      1  
45208                 0            0            0         0      1  
45209                 1            0            0         0      0  
45210                 0            0            0         0      0  

[45211 rows x 43 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 43 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  45211 non-null  int64
 1   balance              45211 non-null  int64
 2   day                  45211 non-null  int64
 3   duration             45211 non-null  int64
 4   campaign             45211 non-null  int64
 5   pdays                45211 non-null  int64
 6   previous             45211 non-null  int64
 7   job_blue-collar      45211 non-null  uint8
 8   job_entrepreneur     45211 non-null  uint8
 9   job_housemaid        45211 non-null  uint8
 10  job_management       45211 non-null  uint8
 11  job_retired          45211 non-null  uint8
 12  job_self-employed    45211 non-null  uint8
 13  job_services         45211 non-null  uint8
 14  job_student          45211 non-null  uint8
 15  job_technician       45211 non-null  uint8
 16  job_unemployed       4

In [8]:
x=df.iloc[:,0:43]
y= df['y_yes'] 


In [9]:
x

age  balance  day  duration  campaign  pdays  previous  \
0       58     2143    5       261         1     -1         0   
1       44       29    5       151         1     -1         0   
2       33        2    5        76         1     -1         0   
3       47     1506    5        92         1     -1         0   
4       33        1    5       198         1     -1         0   
...    ...      ...  ...       ...       ...    ...       ...   
45206   51      825   17       977         3     -1         0   
45207   71     1729   17       456         2     -1         0   
45208   72     5715   17      1127         5    184         3   
45209   57      668   17       508         4     -1         0   
45210   37     2971   17       361         2    188        11   

       job_blue-collar  job_entrepreneur  job_housemaid  ...  month_nov  \
0                    0                 0              0  ...          0   
1                    0                 0              0  ...          0   
2                    0                 1              0  ...          0   
3                    1                 0              0  ...          0   
4                    0                 0              0  ...          0   
...                ...               ...            ...  ...        ...   
45206                0                 0              0  ...          1   
45207                0                 0              0  ...          1   
45208                0                 0              0  ...          1   
45209                1                 0              0  ...          1   
45210                0                 1              0  ...          1   

       month_oct  month_sep  poutcome_other  poutcome_success  \
0              0          0               0                 0   
1              0          0               0                 0   
2              0          0               0                 0   
3              0          0               0                 0   
4              0          0               0                 0   
...          ...        ...             ...               ...   
45206          0          0               0                 0   
45207          0          0               0                 0   
45208          0          0               0                 1   
45209          0          0               0                 0   
45210          0          0               1                 0   

       poutcome_unknown  default_yes  housing_yes  loan_yes  y_yes  
0                     1            0            1         0      0  
1                     1            0            1         0      0  
2                     1            0            1         1      0  
3                     1            0            1         0      0  
4                     1            0            0         0      0  
...                 ...          ...          ...       ...    ...  
45206                 1            0            0         0      1  
45207                 1            0            0         0      1  
45208                 0            0            0         0      1  
45209                 1            0            0         0      0  
45210                 0            0            0         0      0  

[45211 rows x 43 columns]

In [10]:
y

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: y_yes, Length: 45211, dtype: uint8

# Split the dat into training and testing dataset


In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.70,random_state=142)

In [12]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((31647, 43), (13564, 43), (31647,), (13564,))

# Build and train the model 


In [13]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [14]:
ytrain_predict=model.predict(x_train)
ytrain_predict

array([1, 0, 0, ..., 1, 0, 1], dtype=uint8)

In [15]:
model.predict_proba(x_train)

array([[0.118241  , 0.881759  ],
       [0.91076017, 0.08923983],
       [0.69873383, 0.30126617],
       ...,
       [0.08208152, 0.91791848],
       [0.98806957, 0.01193043],
       [0.17496605, 0.82503395]])

#### Calculate the metrics for TRAINING DATA

In [16]:
confusion_matrix(y_train,ytrain_predict)

array([[27761,   206],
       [  779,  2901]], dtype=int64)

In [17]:
print(classification_report(y_train,ytrain_predict))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98     27967
           1       0.93      0.79      0.85      3680

    accuracy                           0.97     31647
   macro avg       0.95      0.89      0.92     31647
weighted avg       0.97      0.97      0.97     31647

